### ISSUE TITLE
Error: 0: the requested global was not found in the registry

### ISSUE THREAD

**Issue by anoadragon453** [danyspin97/wpaperd#46] opened 2023-10-19 19:39 UTC
When I run `wpaperd` on my Wayland GNOME session with two displays (one horizontal, one vertical) I get the following error:

```
➜ RUST_BACKTRACE=full ./target/debug/wpaperd
Error: 
   0: the requested global was not found in the registry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 5 frames hidden ⋮                               
   6: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual::h7fbd2f727851430a
      at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1962
   7: wpaperd::wpaperd::Wpaperd::new::h0226663c4c37f4f5
      at /home/user/code/wpaperd/daemon/src/wpaperd.rs:47
        45 │             output_state: OutputState::new(globals, qh),
        46 │             shm_state,
        47 >             layer_state: LayerShell::bind(globals, qh)?,
        48 │             registry_state: RegistryState::new(globals),
        49 │             surfaces: Vec::new(),
   8: wpaperd::run::h7b4487f2a6defd96
      at /home/user/code/wpaperd/daemon/src/main.rs:78
        76 │     let _hotwatch = setup_hotwatch(&wallpaper_config_file, wallpaper_config.clone(), ev_tx);
        77 │ 
        78 >     let mut wpaperd = Wpaperd::new(
        79 │         &qh,
        80 │         &globals,
   9: wpaperd::main::h8f010fdc51808385
      at /home/user/code/wpaperd/daemon/src/main.rs:212
       210 │     logger.start()?;
       211 │ 
       212 >     if let Err(err) = run(config, xdg_dirs) {
       213 │         error!("{err:?}");
       214 │         Err(err)
  10: core::ops::function::FnOnce::call_once::hd45bde0171a3f6fb
      at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250
                                ⋮ 16 frames hidden ⋮ 
```

and my `~/.config/wpaperd/wallpaper.toml`:

```toml
[default]
apply-shadow = true
duration = "360m"
path = "/home/user/Pictures/wallpapers/"
```

This is running with 94023bf835578b672f4f811ac84266ad5ee86444, built with Rust 1.73.0. Further debugging information:

<details>

<summary>Click to show <code>wayland-info</code> output</summary>

```
➜ wayland-info                                   
interface: 'wl_compositor',                              version:  5, name:  1
interface: 'wl_drm',                                     version:  2, name:  2
interface: 'wl_shm',                                     version:  1, name:  3
        formats (fourcc):
        0x48344258 = 'XB4H'
        0x48344241 = 'AB4H'
        0x48345258 = 'XR4H'
        0x48345241 = 'AR4H'
        0x30334258 = 'XB30'
        0x30334241 = 'AB30'
        0x30335258 = 'XR30'
        0x30335241 = 'AR30'
        0x36314752 = 'RG16'
        0x34324258 = 'XB24'
        0x34324241 = 'AB24'
                 1 = 'XR24'
                 0 = 'AR24'
interface: 'wl_output',                                  version:  4, name:  4
        name: DP-1
        description: BenQ Corporation 32"
        x: 0, y: 690, scale: 2,
        physical_width: 700 mm, physical_height: 390 mm,
        make: 'BNQ', model: 'BenQ EW3270U',
        subpixel_orientation: unknown, output_transform: normal,
        mode:
                width: 3840 px, height: 2160 px, refresh: 60.023 Hz,
                flags: current
interface: 'zxdg_output_manager_v1',                     version:  3, name:  6
        xdg_output_v1
                output: 32
                name: 'HDMI-1'
                description: 'BenQ Corporation 32"'
                logical_x: 3840, logical_y: 0
                logical_width: 2160, logical_height: 3840
        xdg_output_v1
                output: 4
                name: 'DP-1'
                description: 'BenQ Corporation 32"'
                logical_x: 0, logical_y: 690
                logical_width: 3840, logical_height: 2160
interface: 'wl_data_device_manager',                     version:  3, name:  7
interface: 'zwp_primary_selection_device_manager_v1',    version:  1, name:  8
interface: 'wl_subcompositor',                           version:  1, name:  9
interface: 'xdg_wm_base',                                version:  4, name: 10
interface: 'gtk_shell1',                                 version:  5, name: 11
interface: 'wp_viewporter',                              version:  1, name: 12
interface: 'wp_fractional_scale_manager_v1',             version:  1, name: 13
interface: 'zwp_pointer_gestures_v1',                    version:  3, name: 14
interface: 'zwp_tablet_manager_v2',                      version:  1, name: 15
interface: 'wl_seat',                                    version:  8, name: 16
        name: seat0
        capabilities: pointer keyboard
        keyboard repeat rate: 33
        keyboard repeat delay: 500
interface: 'zwp_relative_pointer_manager_v1',            version:  1, name: 17
interface: 'zwp_pointer_constraints_v1',                 version:  1, name: 18
interface: 'zxdg_exporter_v2',                           version:  1, name: 19
interface: 'zxdg_importer_v2',                           version:  1, name: 20
interface: 'zxdg_exporter_v1',                           version:  1, name: 21
interface: 'zxdg_importer_v1',                           version:  1, name: 22
interface: 'zwp_linux_dmabuf_v1',                        version:  4, name: 23
        main device: 0xE280 (/dev/dri/card0 or /dev/dri/renderD128)
        tranche
                target device: 0xE280 (/dev/dri/card0 or /dev/dri/renderD128)
                flags: none
                formats (fourcc) and modifiers (names):
                0x34325241 = 'AR24'; 0x00ffffffffffffff = INVALID
                0x34324241 = 'AB24'; 0x00ffffffffffffff = INVALID
                0x34325258 = 'XR24'; 0x00ffffffffffffff = INVALID
                0x34324258 = 'XB24'; 0x00ffffffffffffff = INVALID
                0x30335241 = 'AR30'; 0x00ffffffffffffff = INVALID
                0x30334241 = 'AB30'; 0x00ffffffffffffff = INVALID
                0x30335258 = 'XR30'; 0x00ffffffffffffff = INVALID
                0x30334258 = 'XB30'; 0x00ffffffffffffff = INVALID
                0x36314752 = 'RG16'; 0x00ffffffffffffff = INVALID
                0x48344241 = 'AB4H'; 0x00ffffffffffffff = INVALID
                0x48344258 = 'XB4H'; 0x00ffffffffffffff = INVALID
interface: 'wp_single_pixel_buffer_manager_v1',          version:  1, name: 24
interface: 'zwp_keyboard_shortcuts_inhibit_manager_v1',  version:  1, name: 25
interface: 'zwp_text_input_manager_v3',                  version:  1, name: 26
interface: 'wp_presentation',                            version:  1, name: 27
        presentation clock id: 1 (CLOCK_MONOTONIC)
interface: 'xdg_activation_v1',                          version:  1, name: 28
interface: 'wl_output',                                  version:  4, name: 32
        name: HDMI-1
        description: BenQ Corporation 32"
        x: 3840, y: 0, scale: 2,
        physical_width: 700 mm, physical_height: 390 mm,
        make: 'BNQ', model: 'BenQ EW3270U',
        subpixel_orientation: unknown, output_transform: 90°,
        mode:
                width: 3840 px, height: 2160 px, refresh: 59.996 Hz,
                flags: current preferred
```

</details>

<details>

<summary>Click to show <code>xrandr</code> output</summary>

```
➜ xrandr
Screen 0: minimum 16 x 16, current 6000 x 3840, maximum 32767 x 32767
DP-1 connected primary 3840x2160+0+690 (normal left inverted right x axis y axis) 700mm x 390mm
   3840x2160     60.00*+
   2048x1536     59.95  
   1920x1440     59.97  
   1600x1200     59.96  
   1440x1080     59.99  
   1400x1050     59.98  
   1280x1024     59.89  
   1280x960      59.94  
   1152x864      59.96  
   1024x768      59.92  
   800x600       59.86  
   640x480       59.38  
   320x240       59.52  
   2560x1600     59.99  
   1920x1200     59.96  
   1680x1050     59.95  
   1440x900      59.89  
   1280x800      59.81  
   1152x720      59.97  
   960x600       59.96  
   928x580       59.88  
   800x500       59.50  
   768x480       59.90  
   720x480       59.71  
   640x400       59.95  
   320x200       58.96  
   3200x1800     59.99  
   2880x1620     60.00  
   2560x1440     59.96  
   2048x1152     59.98  
   1920x1080     59.96  
   1600x900      59.95  
   1368x768      59.88  
   1280x720      59.86  
   1024x576      59.90  
   864x486       59.92  
   720x400       59.55  
   640x350       59.77  
HDMI-1 connected 2160x3840+3840+0 left (normal left inverted right x axis y axis) 700mm x 390mm
   3840x2160     59.98*+
   2048x1536     59.95  
   1920x1440     59.90  
   1600x1200     59.87  
   1440x1080     59.99  
   1400x1050     59.98  
   1280x1024     59.89  
   1280x960      59.94  
   1152x864      59.96  
   1024x768      59.92  
   800x600       59.86  
   640x480       59.38  
   320x240       59.52  
   2560x1600     59.94  
   1920x1200     59.88  
   1680x1050     59.95  
   1440x900      59.89  
   1280x800      59.81  
   1152x720      59.75  
   960x600       59.63  
   928x580       59.88  
   800x500       59.50  
   768x480       59.90  
   720x480       59.71  
   640x400       59.95  
   320x200       58.96  
   3200x1800     59.96  
   2880x1620     59.96  
   2560x1440     59.96  
   2048x1152     59.90  
   1920x1080     59.96  
   1600x900      59.95  
   1368x768      59.88  
   1280x720      59.86  
   1024x576      59.90  
   864x486       59.92  
   720x400       59.55  
   640x350       59.77
```

</details>

Let me know if you need any more info.

**Comment by danyspin97** [comment] 2023-10-30 09:10
Hello @anoadragon453 and thanks for the detailed report. I have developed wpaperd using wayland protocols implemented by wlroots and I hadn't tried it in GNOME yet. I can reproduce it as well so I think that the issue is more design based rather than a bug.

Unfortunately, I don't have any experience with the difference between wlroots and GNOME, I am not sure it is possible to make it work for both.

**Comment by anoadragon453** [comment] 2023-10-30 11:10
That's alright, and thank you for this software.
Perhaps in the meantime it may be worth calling out in the README that this software is only intended to work on `wlroots`-based wayland compositors?

**Comment by danyspin97** [comment] 2024-04-16 12:05
Hello @anoadragon453, I have finally updated the README and added a big notice about compositor supported by wpaperd. Thank you for opening this issue and making me notice this 😄 

Fixed by https://github.com/danyspin97/wpaperd/commit/8f1555cdcb559879abb357ae7cd945332ae21f5f.

**Closed by danyspin97** 2024-04-16 12:05 UTC

**Comment by anoadragon453** [comment] 2024-04-16 15:21
No worries, thank you for your work!
